import { StyleSheet, Dimensions, Platform } from 'react-native';

import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
  listenOrientationChange as loc,
  removeOrientationListener as rol,
} from 'react-native-responsive-screen';

const width_x = Dimensions.get('window').width;
// const heigth_y = Dimensions.get('window').heigth;

const app = StyleSheet.create({
	// Cores globais
	one_color: {
		backgroundColor: '#3B9CE2',
	},
	two_color: {
		backgroundColor: '#4AACCF',
	},
	white_color: {
		backgroundColor: '#fff',
	},
	three_color: {
		backgroundColor: '#D1E2EE',
	},
	four_color: {
		backgroundColor: '#7AACCF',
	},
  //  Titulo
  container: {
    alignItems: 'center',
    flex: 1,
  },
  container_banner: {
    alignItems: 'center',
    width: wp('100%'),
    // marginBottom: '2%',
  },
	item_side: {
		width: wp('100%'),
		alignContent: 'space-between',
		flexDirection: 'row',
	},
	text_wrapper: {
		width: wp('100%'),
		alignItems: 'center',
		alignContent: 'center',
		textAlign: 'center',
	},
	text_title: {
		fontSize: hp('5%'),
	},
	text_banner: {
		fontSize: wp('4%'),
		color: '#fff',
		textAlign: 'center',
		fontFamily: 'ebrima',
		paddingHorizontal: '1%',
		paddingVertical: '3%',
	},
  // Coleta
  container_items: {
    alignContent: 'space-between',
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: wp('100%'),
    justifyContent: 'center',
  },
	picker_wrapper: {
		padding: wp('1%'),
		marginHorizontal: wp('2%'),
		margin: hp('3%'),
		borderRadius: 5,
		backgroundColor: 'rgba(255,255,255,.9)',
		elevation: 1,
	},
	picker: {
		height: hp('5%'),
		width: wp('40%'),
		fontSize: wp('4%'),
		color: '#000',
		// backgroundColor: 'rgba(255,255,255,.9)',
	},
  // Estabelecimentos
  container_scroll: {
    width: wp('100%'),
		marginBottom: hp('1%'),
	},
  container_list: {
    flexDirection: 'row',
		justifyContent: 'space-evenly',
    flexWrap: 'wrap',
		width: wp('90%'),
		backgroundColor: 'rgba(255,255,255,0.8)',
		marginLeft: wp('5%'),
		borderRadius: 5,
		padding: wp('3%'),
		elevation: 4,
  },
  container_icon: {
    padding: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: wp('50%'),
  },
  container_icon_button: {
    flexDirection: 'row',
		backgroundColor: 'rgba(255,255,255,0.8)',
    marginBottom: hp('1%'),
		width: wp('55%'),
		justifyContent: 'space-evenly',
		// marginLeft: wp('60%'),
		padding: 5,
		paddingBottom: 10,
		marginLeft: wp('5%'),
		borderRadius: 5,
		marginTop: hp('1%'),
		elevation: 4,
		alignContent: 'center',
	},
	container_icon_text: {
		color: '#000',
		// fontWeight: 'bold',
		fontSize: wp('3%'),
		marginTop: hp('0%'),
		// marginLeft: hp('1%'),
		fontFamily: 'times',
		textAlign: 'center',
	},
	text_icon: {
		color: '#fff',
		fontWeight: 'bold',
		fontSize: wp('2.8%'),
		marginTop: hp('1.5%'),
		marginLeft: hp('1%'),
		textAlign: 'center',
	},
	text_list: {
		color: '#fff',
		fontWeight: 'bold',
		fontSize: wp('3.5%'),
		fontFamily: 'Ebrima',
		// marginTop: hp('0.5%%'),
		// marginLeft: hp('5%'),
		// width: wp('43%'),
		padding: 3,
	},
	text_list_first: {
		color: '#fff',
		fontWeight: 'bold',
		fontSize: wp('3.5%'),
		fontFamily: 'Ebrima',
		// marginTop: hp('0.5%'),
		// marginLeft: hp('5%'),
		// width: wp('28%'),
		padding: 3,
	},
	text_list_container: {
		justifyContent: 'center',
		alignItems: 'center',
		width: '100%',
		flexDirection: 'row',
		flexWrap: 'wrap',
    borderRadius: 3,
		backgroundColor: '#3B9CE2',
		margin: 3,
  },
  // Coleta modal
  modal_view: {
    width: wp('100%'),
		height: hp('100%'),
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal_content: {
    justifyContent: 'center',
    alignItems: 'center',
    // paddingVertical: hp('0.5%'),
    backgroundColor: 'rgba(255,255,255,0.8)',
  },
	modal_title: {
    width: wp('100%'),
		padding: 15,
    fontSize: wp('4%'),
    color: '#fff',
    textAlign: 'center',
		fontFamily: 'Ebrima',
    fontWeight: 'bold',
		textTransform: 'uppercase',
  },
  text: {
    padding: 10,
    fontSize: wp('4%'),
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'times',
	},
  text_small: {
    fontSize: wp('3.5%'),
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'times',
    fontWeight: 'bold',
	},
  //   LOGO
  logo: {
    width: 100,
    height: 115,
    resizeMode: 'stretch',
    marginBottom: 15,
  },
  logo_small: {
    width: hp('6%'),
    height: hp('6%'),
    resizeMode: 'stretch',
    marginBottom: 15,
    marginTop: hp('2%'),
  },
  //   BOTÕES
  button: {
		borderRadius: 10,
    alignItems: 'center',
    padding: 5,
    marginTop: 10,
    // width: wp('50%'),
  },
  open_button: {
    width: wp('30%'),
    borderRadius: 5,
    padding: 10,
    elevation: 2,
    textAlign: 'center',
    backgroundColor: '#fff',
  },
	text_button: {
		fontSize: hp('2.3%'),
		color: '#3B9CE2',
		fontFamily: 'Georgia',
	},
  modal_button: {
    right: wp('10%'),
    top: hp('2%'),
    position: 'absolute',
		width: wp('12%'),
    borderRadius: 5,
		padding: wp('2%'),
		textAlign: 'center',
		backgroundColor: '#2196F3',
	},
	logout_button: {
		right: wp('10%'),
		top: hp('2%'),
		position: 'absolute',
		width: wp('12%'),
		borderRadius: 50,
		padding: wp('2%'),
		textAlign: 'center',
		alignContent: 'center',
		alignItems: 'center',
		backgroundColor: '#2196F3',
	},
	refresh_button: {
		right: wp('25%'),
		top: hp('2%'),
		position: 'absolute',
		width: wp('12%'),
		borderRadius: 50,
		padding: wp('2%'),
		textAlign: 'center',
		alignContent: 'center',
		alignItems: 'center',
		backgroundColor: '#2196F3',
	},
	refresh_button_login: {
		right: wp('5%'),
		top: hp('2%'),
		position: 'absolute',
		width: wp('11%'),
		borderRadius: 100,
		padding: wp('2%'),
		textAlign: 'center',
		alignContent: 'center',
		alignItems: 'center',
		// backgroundColor: '#2196F3',
		backgroundColor: '#fff',
	},
	info_button_login: {
		right: wp('20%'),
		top: hp('2%'),
		position: 'absolute',
		width: wp('11%'),
		borderRadius: 100,
		padding: wp('2%'),
		textAlign: 'center',
		alignContent: 'center',
		alignItems: 'center',
		// backgroundColor: '#2196F3',
		backgroundColor: '#fff',
	},
  button_wrap: {
    alignContent: 'space-between',
    flexDirection: 'row',
  },
  button_product: {
    borderRadius: 5,
    alignItems: 'center',
    paddingVertical: '3%',
    paddingHorizontal: '5%',
    margin: 5,
    fontSize: wp('4%'),
    borderWidth: 1,
    borderColor: '#fff',
    fontFamily: 'times',
    color: '#fff',
    width: wp('33.33%'),
    textAlign: 'center',
  },
  button_item: {
    textAlign: 'center',
    borderRadius: 5,
    padding: '3%',
    marginTop: hp('1.5%'),
    marginBottom: hp('1.7%'),
    borderWidth: 1,
    fontWeight: 'bold',
    borderColor: '#fff',
  },
	button_menu_margin: {
		margin: 11,
		marginTop: hp('10%'),
	},
  button_menu: {
	  textAlign: 'center',
	  borderRadius: 5,
	  alignItems: 'center',
	  paddingVertical: '3%',
	  paddingHorizontal: '5%',
	  fontSize: wp('4%'),
	  borderWidth: 1,
	  borderColor: '#fff',
	  backgroundColor: '#fff',
	  width: wp('40%'),
	  fontFamily: 'times',
  },
  //   INPUT
  text_input: {
	  height: 50,
	  padding: wp('3%'),
	  // borderColor: '#fff',
	  // borderWidth: 2,
	  marginBottom: 10,
	  marginTop: 10,
	  fontFamily: 'times',
	  color: '#000',
	  width: wp('65%'),
	  borderRadius: 10,
	  backgroundColor: 'rgba(255,255,255,1)',
  },
  input_modal: {
	  borderWidth: 1,
	  borderColor: '#fff',
		margin: 5,
	  borderRadius: 5,
		width: wp('25%'),
	  padding: 10,
		fontSize: wp('3.5%'),
		color: '#000',
	  textAlign: 'center',
	  fontFamily: 'times',
		backgroundColor: "#fff",
	},
	alert_view: {
		// flex: 1,
		// width: wp('100%'),
		height: hp('100%'),
		backgroundColor: 'rgba(0,0,0,0.4)',
		justifyContent: 'center',
		alignItems: 'center',
		zIndex: -1,
	},
	alert_content: {
		// flex: 1,
		// zIndex: 10,
		backgroundColor: 'rgba(255,255,255,0.9)',
		position: 'absolute',
		top: hp('30%'),
		left: wp('2.5%'),
		// height: hp('20%'),
		width: wp('95%'),
		justifyContent: 'center',
		alignItems: 'center',
		padding: wp('5%'),
		borderRadius: 5,
		elevation: 1,
	},
	alert_message: {
		fontSize: wp('4%'),
		fontFamily: 'Georgia',
		marginBottom: wp('10%'),
		marginTop: wp('5%'),
		textAlign: 'center',
	},
	alert_title: {
		fontSize: wp('4.5%'),
		fontFamily: 'Georgia',
		marginTop: wp('5%'),
		// textAlign: 'left',
	},
});

export default app;
